/**
 * @looprun-ai/core — the DOMAIN-NEUTRAL assembled prompt renderer + the `DomainContract` interface (framework-free).
 *
 * This file contains ZERO business content — it is pure assembly machinery. Every business string
 * comes from a GENERATED artifact with exactly one owner: the AgentSpec (persona / Flow / rule sections /
 * Governance / Behavior — per-agent) or the host-injected `DomainContract` (voice / core invariants /
 * language / state-render mapping — common to a business's agents). The per-agent persona (role line,
 * persona-on-spec law) lives on `spec.persona` and renders as the FIRST Behavior bullet; the shared
 * business `voice` lives on the domain and opens the assembled prompt — byte-identical across the domain's agents
 * (shared-prefix law: maximal shared prefix, per-agent divergence as late as possible).
 *
 * State-in-tail: `renderAssembledPrompt` renders ONLY case-invariant content, so the assembled
 * system prompt is BYTE-STABLE across cases/turns of an agent (→ cacheable prefix). The volatile
 * account/brand STATE (`domain.stateBlock`) is NOT rendered here — the runtime rides it on the USER
 * MESSAGE tail (like upload labels), keeping the stable prefix intact. For that to hold, a spec's
 * `persona` MUST be case-invariant (do not interpolate volatile world state into it).
 *
 * PROVENANCE The renderer does not build strings and join them. It builds a typed,
 * attributed table — {@link PromptBlock}[] of {@link PromptRow}s of {@link PromptLine}s — and the assembled prompt
 * string is a pure FOLD over that table ({@link foldPrompt}). A bare `parts.join('\n\n')` is the
 * point where every trace of who-said-what dies, which is precisely why contradictions between
 * sections (and between the assembled prompt and the tool schemas the model also reads) would be structurally
 * unaskable. See `prompt-fold.ts` for the table's shape and the fold that renders it.
 */
import { resolveBindings } from './spec.js';
import type { AgentSpec, GuardBinding, Hook, Priority } from './spec.js';
import type { AgentWorld, Guard } from './rules.js';
import type { CoreOutcome, OutcomeMap, RenderedClaim } from './runtime/claims.js';
import type { EngineText } from './runtime/engine-text.js';
import type { SensitiveMode } from './runtime/sensitive-filter.js';
import { derivePolarity, deriveSubject, foldPrompt, proseKey, proseText } from './prompt-fold.js';
import type { SubjectRule, PromptBlock, PromptLine, PromptRow } from './prompt-fold.js';

export type { SubjectRule, PromptBlock, PromptLine, PromptRow } from './prompt-fold.js';

/** A named tool set a {@link ContractGuardBinding} may target. Each installing lane resolves the name
 *  against its own declarations at construction:
 *    · `'writeTools'`        — `contract.writeTools ∩ lane.tools − exempt` (the write surface is
 *                              contract-wide; the lane keeps only what it carries);
 *    · `'destructiveTools'`  — `lane.destructiveTools − exempt` (destructiveness is decided per desk,
 *                              so the set is the INSTALLING lane's own declaration).
 *  A lane whose resolution comes out empty installs nothing. */
export type DeclaredToolSet = 'writeTools' | 'destructiveTools';

/** ONE guard declaration on the domain contract, installed by every lane that carries its target.
 *  The `target` names literal tools or a {@link DeclaredToolSet}; either way it expands to a literal
 *  `string[]` at install time — a `ToolTarget` never carries a set name. `exempt` withdraws names from
 *  a NAMED set only (a literal list simply omits the tool); an exempt name outside the set throws at
 *  construction. `priority` defaults to `agent`; contract bindings install during the spec
 *  constructor, so within a tier they precede every lane-added binding. */
export interface ContractGuardBinding {
  hook: Hook;
  target: string[] | DeclaredToolSet;
  guard: Guard;
  id: string;
  priority?: Priority;
  exempt?: string[];
}

/** The DOMAIN skin: the business-COMMON strings NOT derived from any single AgentSpec. Host-injected
 *  and, at best, GENERATED by the agentspec skill from the business docs. Carries NO
 *  per-agent persona — that lives on `spec.persona` (persona-on-spec law). */
export interface DomainContract {
  /** The business VOICE paragraph — the assembled prompt's opening. BYTE-IDENTICAL across every agent of the
   *  domain (shared-prefix law: shared/static head, per-agent divergence as late as possible) and
   *  case-invariant (no volatile world state — cacheable prefix). */
  voice: string;
  /** The volatile account/brand-state block — rendered by the runtime onto the USER MESSAGE tail. */
  stateBlock(world: AgentWorld): string;
  /** The "## Core rules (NEVER violate)" invariants — DOMAIN-wide and rendered verbatim into every
   *  agent of the domain. Nothing agent-specific belongs here (agent scope lives on `spec.scope`;
   *  per-tool protocol prose is already composed, scoped to the owner, into that tool's own
   *  description by `composeToolDescription`). */
  coreInvariants: string[];
  /** The final "## Output language (ABSOLUTE)" clause. */
  languageClause: string;
  /** Deterministic honest-abstain closure (verified observations only) — an OVERRIDE seam: when present it
   *  replaces the engine's default derive-and-render exhaustion closure, receiving the same evidence
   *  (world, the turn's domain tool names, produced labels, the violation kinds). */
  exhaustionReply?: (world: AgentWorld, okTools: string[], produced: string[], violations: string[]) => string;
  /** The domain's WORDING (and language) for ONE verified claim in the user-facing operation report —
   *  the domain language seam over {@link renderOperationReport}. Given the VERIFIED fields of a claim
   *  ({@link RenderedClaim}: `target`/`outcome`/`amount`, never the agent-authored advisory `op`) and its
   *  resolved core outcome, return the one-liner the user reads. Absent ⇒ the engine's neutral English
   *  default (which renders the claim's `target` and nothing else). */
  renderClaim?: (claim: RenderedClaim, core: CoreOutcome) => string;
  /** The ENGINE's own user-facing sentences — the record closures and the consent question. The engine
   *  puts these on the user's screen itself, so a conversation held in another language declares them
   *  here. Partial: what is not declared falls back per key to the engine's English. Distinct from
   *  {@link renderClaim}, which words one CLAIM; this words what the engine says around them, and the
   *  consent question is the part that has to be readable — the user types its token back. */
  engineText?: Partial<EngineText>;
  /** The domain's WRITE tools — the ones that MUTATE the world (vs pure reads). The honesty cross-check
   *  (`claimIsGrounded` / `claimIsComplete`, auto-installed when this is non-empty) reads it to ground a
   *  `success` claim against an EFFECTED write and to demand every effected write be reported. Same list
   *  `deriveClaimsFromActionHistory` consumes so the exhaustion closure never announces a no-effect simulate as done —
   *  seated HERE so both the write surface and its {@link outcomes} map arrive together on the one domain object. */
  writeTools?: readonly string[];
  /** The contract's TOOL-GUARD declarations — each installed by every lane whose surface carries the
   *  binding's resolved target (see {@link ContractGuardBinding}). The domain-wide write gate is one of
   *  them: a `precondition` bound to `'writeTools'` at priority `changeAllowed`, declared ONCE so no
   *  lane can key on a third of the condition. */
  guards?: ContractGuardBinding[];
  /** The domain OUTCOME vocabulary: every non-core outcome word an agent may declare in a `did` claim MUST
   *  map to a core outcome (e.g. `{ settled: 'success' }`), so the action history cross-check stays
   *  engine-owned and never becomes semantic. Fed to `claimIsGrounded` beside {@link writeTools}. */
  outcomes?: OutcomeMap;
  /** Fields a result may not carry: `'omit'` deletes, `'mask'` keeps a recognizable masked form.
   *  Dot-suffix paths over result keys. The executor is not trusted to hide anything — this filter
   *  runs on our side of the boundary — and HOW FAR it reaches is decided by the seam the tool
   *  executes on:
   *
   *    · the WORLD seam — the filter runs inside the tool's own `execute`, so the value the model
   *      runtime receives is the filtered one, and the record is filtered with it.
   *    · a SELF-EXECUTING tool (native, MCP) — its `execute` returns straight to the model runtime,
   *      which no engine code sits in front of. The filter reaches the action history and therefore
   *      everything composed from it: the operation record, the closure, the judge envelope, the
   *      sealed turn. The model's own view of that one result is the tool's. */
  sensitiveFields?: Record<string, SensitiveMode>;
  /** Free-text fields (dot-suffix over tool argument and result keys) whose CONTENT is
   *  pattern-scrubbed: emails, Luhn-valid card numbers, conservative phone shapes. A field that
   *  legitimately carries contact data is simply not declared — the acceptance is authored and visible.
   *  On ARGUMENTS the reach is the same on every seam: the scrub rewrites the argument object the
   *  executor is about to receive, so the raw value never leaves the process. On RESULTS it follows
   *  {@link sensitiveFields}. */
  scrubTextFields?: string[];
}

/**
 * @deprecated Use {@link DomainContract}. Renamed: the object is not a visual contract, it is the
 * DOMAIN CONTRACT (the business-common rules every agent of a domain shares). Kept as a compatibility
 * alias for existing consumers. Nothing new may use this name.
 */

/** Options for {@link renderPromptBlocks} — the injected subject lexicon (P8a: business vocabulary
 *  never lives in the runtime). Absent ⇒ only guard-kind-derived subjects are populated. */
export interface PromptRenderOptions {
  lexicon?: readonly SubjectRule[];
}

/** Linearize producer→consumer edges into an ordered node path (agent flows form simple chains). */
export function chainOrder(edges: { from: string; to: string }[]): string[] {
  if (!edges.length) return [];
  const succ = new Map<string, string>();
  const hasPred = new Set<string>();
  for (const e of edges) {
    succ.set(e.from, e.to);
    hasPred.add(e.to);
  }
  const start = edges.map((e) => e.from).find((n) => !hasPred.has(n)) ?? edges[0].from;
  const order: string[] = [];
  const seen = new Set<string>();
  let cur: string | undefined = start;
  while (cur && !seen.has(cur)) {
    order.push(cur);
    seen.add(cur);
    cur = succ.get(cur);
  }
  return order;
}

// ── PromptLine / PromptRow constructors ────────────────────────────────────────

function line(
  owner: string,
  section: string | null,
  text: string,
  opts?: { guardKind?: string; hook?: Hook; target?: 'any' | readonly string[]; lexicon?: readonly SubjectRule[] },
): PromptLine {
  return {
    owner,
    section,
    ...(opts?.hook ? { hook: opts.hook } : {}),
    ...(opts?.target ? { target: opts.target } : {}),
    subject: deriveSubject(text, { guardKind: opts?.guardKind, lexicon: opts?.lexicon }),
    polarity: derivePolarity(text),
    text,
  };
}

/** A row that is exactly one line, with an optional bullet prefix / terminal punctuation. */
const row = (l: PromptLine, prefix = '', suffix = ''): PromptRow => ({ prefix, sep: '', suffix, lines: [l] });

// ── Sections ─────────────────────────────────────────────────────────────────

const SECTION_GLOBAL_TOOL = '## Global tool rules';
const SECTION_REPLY = '## Reply rules (govern the message you send — checked on every reply)';
/**
 * `onInput` prose gets its OWN heading, separate from `## Reply rules`. The reply heading tells the
 * model the rule governs "the message you send — checked on every reply", and for an INPUT rule that is
 * simply false: an input rule is checked on the INCOMING message, before the model acts, and a turn it
 * rejects never reaches a reply at all. A heading that misdescribes its own contents is the same defect
 * class as prose that misdescribes its check (the prose≠reason law).
 *
 * BYTE-FREE for every shipping bundle: no generated bundle installs an `onInput` guard, so this block
 * is absent and the assembled prompt is unchanged. It is placed immediately BEFORE `## Reply rules`
 * (after `## Global tool rules`, before `## Governance`) so the shared-prefix ordering is untouched.
 */
const SECTION_INPUT = '## Input rules (govern the incoming message — checked before you act)';

/**
 * THE PROSE-RENDERING RULE ("no guard prose the model cannot read").
 *
 * EVERY guard's `prose()` reaches the model. The binding's TARGET decides WHERE it lands, never
 * WHETHER it is shown:
 *
 *   - binding `target` names TOOLS (any hook)      → the tool's OWN description (`composeToolDescription`)
 *   - binding `target === 'any'`, preTool/postTool → `## Global tool rules`
 *   - binding `target === 'any'`, onInput          → `## Input rules`
 *   - binding `target === 'any'`, onReply          → `## Reply rules`
 *
 * The assembled prompt therefore carries ONLY the `target:'any'` sections; a tool-scoped rule lives
 * beside the schema of the one tool it governs, where the model reads it at the moment of choosing
 * the call. Per-tool de-duplication lives in `composeToolDescription`.
 *
 * `onReplyMutate` carries NO prose BY CONSTRUCTION — a `ReplyMutator` is `{ kind, apply }` with no
 * `prose()`: it is not a rule the model must follow but a deterministic egress rewrite that cannot fail
 * and needs no model cooperation. Nothing is hidden from the model, so the rule is not violated. See
 * GUARDS.md §2.
 *
 * Section ORDER keeps the assembled prompt head static (shared-prefix law): the reply/input sections are placed
 * AFTER `## Global tool rules` and BEFORE `## Governance`, so per-agent divergence still enters as late as
 * possible.
 *
 * DE-DUPLICATION here is `emitted` — shared by `## Global tool rules` → `## Input rules` →
 * `## Reply rules`, in that order. It covers only the `target:'any'` sections this renderer emits;
 * a tool description's rules are de-duplicated per tool, in `composeToolDescription`, so a prose
 * bound to five tools renders five times, once per description. The arbiter is byte-identity: every
 * emitted copy carries its own owner provenance (`prompt-fold.ts`), so a caller can count
 * duplication per subject rather than infer it from the bytes.
 */
function ruleBlocks(spec: AgentSpec, opts?: PromptRenderOptions): PromptBlock[] {
  const lexicon = opts?.lexicon;
  const toolHookBindings: Array<GuardBinding & { hook: Hook }> = [
    ...resolveBindings(spec.guards.preTool).map((b) => ({ ...b, hook: 'preTool' as Hook })),
    ...resolveBindings(spec.guards.postTool).map((b) => ({ ...b, hook: 'postTool' as Hook })),
  ];
  const inputBindings = resolveBindings(spec.guards.onInput).map((b) => ({ ...b, hook: 'onInput' as Hook }));
  const replyBindings = resolveBindings(spec.guards.onReply).map((b) => ({ ...b, hook: 'onReply' as Hook }));

  const emitted = new Set<string>();

  /** The `target:'any'` sections share `emitted`, in call order (globals → input → reply). */
  const anySection = (
    bindings: Array<GuardBinding & { hook: Hook }>,
    section: string,
  ): PromptBlock | null => {
    const rows: PromptRow[] = [];
    for (const b of bindings) {
      if (b.target !== 'any') continue;
      const p = b.guard.prose();
      if (!p?.trim() || emitted.has(proseKey(p))) continue;
      emitted.add(proseKey(p));
      rows.push(
        row(
          line(`guard:${b.guard.kind}`, section, proseText(p), { guardKind: b.guard.kind, hook: b.hook, target: 'any', lexicon }),
          '- ',
          '.',
        ),
      );
    }
    return rows.length ? { heading: section, rows } : null;
  };

  const globalBlock = anySection(toolHookBindings, SECTION_GLOBAL_TOOL);
  const inputBlock = anySection(inputBindings, SECTION_INPUT);
  const replyBlock = anySection(replyBindings, SECTION_REPLY);

  return [globalBlock, inputBlock, replyBlock].filter((b): b is PromptBlock => b !== null);
}

/** The `## Scope precedence` block — rendered VERBATIM from the spec's own `scope` declaration (the
 *  runtime derives nothing: no ownership map, no set intersection). Rendered ABOVE core rules
 *  (position is the measured lever). Null when the spec declares no scope. */
function scopeBlock(spec: AgentSpec, opts?: PromptRenderOptions): PromptBlock | null {
  const scope = spec.scope;
  // `others.length === 0` drops the block INCLUDING `scope.lane` — deliberate, not an oversight (audit
  // , finding iii). This block exists to ROUTE ("that belongs to team X"); with no other
  // teams declared there is nothing to route to, and the lane sentence alone would render a
  // `## Scope precedence (OUTRANKS every rule below)` heading over a single line that grants no
  // precedence over anything. An agent that wants to state its lane without routing states it in
  // `persona`, which is where a role line belongs (persona-on-spec law).
  if (!scope || !scope.others.length) return null;
  const heading = '## Scope precedence (OUTRANKS every rule below)';
  const routes = scope.others.map((o) => `${o.label} (${o.covers})`).join(' · ');
  // WORDING CONSTRAINT: the block must not invite the model to
  // narrate its own identity — "I am the billing agent…" trips a spec's self-narration lexicon and
  // the honest reply dies in a redrive/exhaustion stub. State the OWNING TEAM, never the own role.
  const texts = [
    `In scope here: ${scope.lane}. Nothing else.`,
    `Out of scope, owned by other teams: ${routes}.`,
    'When a request is out of scope, the ONLY correct move is to say which team handles it (name that team, never your own role or identity) and stop. Collecting ids or dates for it, checking permissions for it, pricing or drafting it, or offering to do it yourself — even behind a confirmation — IS doing the other team\'s job and is a failure.',
    // This block ROUTES; it never authorises. Measured : without this line
    // the model read "in scope ⇒ comply literally" and dumped both customer records "per your
    // request", where the anchor had asked for the business reason first.
    'In scope means only that the request belongs here — it does NOT authorise an action or a disclosure by itself. Every rule below still governs WHAT you may do and HOW MUCH you may reveal.',
  ];
  return {
    heading,
    rows: texts.map((t) => row(line('spec.scope', heading, t, { lexicon: opts?.lexicon }), '- ')),
  };
}

function governanceBlock(spec: AgentSpec, heading: string, opts?: PromptRenderOptions): PromptBlock | null {
  const directives = spec.controls.directives ?? [];
  if (!directives.length) return null;
  return {
    heading,
    rows: directives.map((d) =>
      row(line('spec.controls.directives', heading, `${d.cond} → ${d.directive}`, { lexicon: opts?.lexicon }), '- IF '),
    ),
  };
}

/**
 * The assembled prompt as an ATTRIBUTED TABLE — the structure `renderAssembledPrompt` folds. Every normative unit
 * carries its owner / section / hook / target / subject / polarity, so the assembled prompt can be QUERIED
 * (contradiction, duplication, single-owner) instead of only read.
 *
 * The `_world`/`_uploads` parameters of the string renderer are absent here by design: nothing in the
 * assembled prompt may depend on volatile state (brand-in-tail).
 */
export function renderPromptBlocks(spec: AgentSpec, domain: DomainContract, opts?: PromptRenderOptions): PromptBlock[] {
  const lexicon = opts?.lexicon;
  const blocks: PromptBlock[] = [];

  blocks.push({ heading: null, rows: [row(line('domain.voice', null, domain.voice, { lexicon }))] });

  const scope = scopeBlock(spec, opts);
  if (scope) blocks.push(scope);

  // Guard the heading on non-empty content, matching scopeBlock: an EMPTY invariant list
  // must not render a bare `## Core rules (NEVER violate)` heading with nothing under it.
  const coreHeading = '## Core rules (NEVER violate)';
  if (domain.coreInvariants.length) {
    blocks.push({
      heading: coreHeading,
      rows: domain.coreInvariants.map((r) => row(line('domain.coreInvariants', coreHeading, r, { lexicon }), '- ')),
    });
  }

  const order = chainOrder(spec.flow);
  if (order.length) {
    const flowHeading = '## Flow (call the tools in THIS order — do not skip a step)';
    blocks.push({ heading: flowHeading, rows: [row(line('spec.flow', flowHeading, order.join(' → '), { lexicon }))] });
  }

  blocks.push(...ruleBlocks(spec, opts));

  const gov = governanceBlock(spec, '## Governance (deterministic — evaluate against the account state below)', opts);
  if (gov) blocks.push(gov);

  // The per-agent persona (role line) leads the Behavior list — the LAST section before language,
  // so agents of a domain share the maximal static prefix (shared-prefix law).
  const behaviorHeading = '## Behavior';
  blocks.push({
    heading: behaviorHeading,
    rows: [
      row(line('spec.persona', behaviorHeading, spec.persona, { lexicon }), '- '),
      ...spec.behavior.map((b) => row(line('spec.behavior', behaviorHeading, b, { lexicon }), '- ')),
    ],
  });

  blocks.push({ heading: null, rows: [row(line('domain.languageClause', null, domain.languageClause, { lexicon }))] });

  return blocks;
}

/**
 * The SCOPED spec assembled prompt — the BYTE-STABLE system prompt: the domain's shared VOICE (byte-identical
 * across the domain's agents — shared-prefix law) + the domain's core invariants + the spec's Flow /
 * Global tool rules / Input rules / Reply rules / Governance / Behavior (the spec's per-agent persona/role
 * line renders as the FIRST Behavior bullet — per-agent divergence as late as possible) + the domain's
 * language clause. Tool-scoped guard prose is NOT here — it lives in each tool's own description
 * (`composeToolDescription`).
 * NO account/brand state (that rides the user message tail — brand-in-tail). `_uploads` is accepted
 * for signature compatibility but not rendered (upload labels also ride the user message).
 *
 * It is now a pure FOLD over {@link renderPromptBlocks} — same bytes, but the intermediate structure
 * survives and can be interrogated.
 */
export function renderAssembledPrompt(
  _world: AgentWorld,
  spec: AgentSpec,
  _uploads: readonly string[] = [],
  domain?: DomainContract,
): string {
  const d = domain ?? spec.contract;
  if (!d) throw new Error('renderAssembledPrompt: a DomainContract is required (pass one, or set spec.contract).');
  return foldPrompt(renderPromptBlocks(spec, d));
}
