/**
 * @looprun-ai/core — the DOMAIN-NEUTRAL trunk renderer + the `DomainContract` interface (framework-free).
 *
 * This file contains ZERO business content — it is pure assembly machinery. Every business string
 * comes from a GENERATED artifact with exactly one owner: the AgentSpec (persona / Flow / Tool rules /
 * Governance / Behavior — per-agent) or the host-injected `DomainContract` (voice / core invariants /
 * language / state-render mapping — common to a business's agents). The per-agent persona (role line,
 * persona-on-spec law) lives on `spec.persona` and renders as the FIRST Behavior bullet; the shared
 * business `voice` lives on the domain and opens the trunk — byte-identical across the domain's agents
 * (trunk-static law: maximal shared prefix, per-agent divergence as late as possible).
 *
 * State-in-tail: `renderScopedSpecTrunk` renders ONLY case-invariant content, so the assembled
 * system prompt is BYTE-STABLE across cases/turns of an agent (→ cacheable prefix). The volatile
 * account/brand STATE (`domain.stateBlock`) is NOT rendered here — the runtime rides it on the USER
 * MESSAGE tail (like upload labels), keeping the stable prefix intact. For that to hold, a spec's
 * `persona` MUST be case-invariant (do not interpolate volatile world state into it).
 *
 * PROVENANCE (2026-07-20). The renderer no longer builds strings and joins them. It builds a typed,
 * attributed table — {@link TrunkBlock}[] of {@link TrunkRow}s of {@link TrunkLine}s — and the trunk
 * string is a pure FOLD over that table ({@link foldTrunk}). Before this, `parts.join('\n\n')` was the
 * point where every trace of who-said-what died, which is precisely why contradictions between
 * sections (and between the trunk and the tool schemas the model also reads) were structurally
 * unaskable. See `coherence.ts` for the table's shape and the queries that now run over it.
 */
import { resolveBindings } from './spec.js';
import type { AgentSpec, GuardBinding, Hook } from './spec.js';
import type { AgentWorld } from './rules.js';
import { derivePolarity, deriveSubject, foldTrunk } from './coherence.js';
import type { SubjectRule, TrunkBlock, TrunkLine, TrunkRow } from './coherence.js';

export type { SubjectRule, TrunkBlock, TrunkLine, TrunkRow } from './coherence.js';

/** The DOMAIN skin: the business-COMMON strings NOT derived from any single AgentSpec. Host-injected
 *  and, in the ideal DX, GENERATED by the agentspec skill from the business docs. Carries NO
 *  per-agent persona — that lives on `spec.persona` (persona-on-spec law). */
export interface DomainContract {
  /** The business VOICE paragraph — the trunk's opening. BYTE-IDENTICAL across every agent of the
   *  domain (trunk-static law: shared/static head, per-agent divergence as late as possible) and
   *  case-invariant (no volatile world state — cacheable prefix). */
  voice: string;
  /** The volatile account/brand-state block — rendered by the runtime onto the USER MESSAGE tail. */
  stateBlock(world: AgentWorld): string;
  /** The "## Core rules (NEVER violate)" invariants — DOMAIN-wide and rendered verbatim into every
   *  agent of the domain. Nothing agent-specific belongs here (agent scope lives on `spec.scope`;
   *  per-tool protocol prose is already emitted, scoped to the owner, by that tool's guards under
   *  "## Tool rules"). */
  coreInvariants: string[];
  /** The final "## Output language (ABSOLUTE)" clause. */
  languageClause: string;
  /** Deterministic honest-abstain closure (verified observations only). */
  exhaustionReply?: (world: AgentWorld, okTools: string[], produced: string[], violations: string[]) => string;
}

/**
 * @deprecated Use {@link DomainContract}. Renamed: the object is not a visual theme, it is the
 * DOMAIN CONTRACT (the business-common rules every agent of a domain shares). Kept as a compatibility
 * alias for existing consumers. Nothing new may use this name.
 */
export type TrunkTheme = DomainContract;

/** Options for {@link renderTrunkBlocks} — the injected subject lexicon (P8a: business vocabulary
 *  never lives in the runtime). Absent ⇒ only guard-kind-derived subjects are populated. */
export interface TrunkRenderOptions {
  lexicon?: readonly SubjectRule[];
}

/** Linearize producer→consumer edges into an ordered node path (agent flows form simple chains). */
export function chainOrder(edges: { from: string; to: string }[]): string[] {
  if (!edges.length) return [];
  const succ = new Map<string, string>();
  const hasPred = new Set<string>();
  for (const e of edges) {
    succ.set(e.from, e.to);
    hasPred.add(e.to);
  }
  const start = edges.map((e) => e.from).find((n) => !hasPred.has(n)) ?? edges[0].from;
  const order: string[] = [];
  const seen = new Set<string>();
  let cur: string | undefined = start;
  while (cur && !seen.has(cur)) {
    order.push(cur);
    seen.add(cur);
    cur = succ.get(cur);
  }
  return order;
}

/** Normalized dedup key for a rendered prose string (trailing punctuation / whitespace / case-insensitive). */
function proseKey(s: string): string {
  return proseText(s).replace(/\s+/g, ' ').toLowerCase();
}

/** A prose string as it is rendered: trimmed, with its own terminal punctuation stripped so the
 *  renderer's own separator (`;` between a tool's rules, `.` at end of line) never doubles up. Some
 *  kinds return their deny `reason` verbatim as `prose()` and those strings are written as sentences. */
function proseText(s: string): string {
  return s.trim().replace(/[.;]+$/, '');
}

// ── TrunkLine / TrunkRow constructors ────────────────────────────────────────

function line(
  owner: string,
  section: string | null,
  text: string,
  opts?: { guardKind?: string; hook?: Hook; target?: 'any' | readonly string[]; tool?: string; lexicon?: readonly SubjectRule[] },
): TrunkLine {
  return {
    owner,
    section,
    ...(opts?.hook ? { hook: opts.hook } : {}),
    ...(opts?.target ? { target: opts.target } : {}),
    ...(opts?.tool ? { tool: opts.tool } : {}),
    subject: deriveSubject(text, { guardKind: opts?.guardKind, lexicon: opts?.lexicon }),
    polarity: derivePolarity(text),
    text,
  };
}

/** A row that is exactly one line, with an optional bullet prefix / terminal punctuation. */
const row = (l: TrunkLine, prefix = '', suffix = ''): TrunkRow => ({ prefix, sep: '', suffix, lines: [l] });

/** A row whose content is several `; `-joined normative fragments (the `## Tool rules` shape). */
const composedRow = (prefix: string, lines: TrunkLine[], suffix: string): TrunkRow => ({ prefix, sep: '; ', suffix, lines });

// ── Sections ─────────────────────────────────────────────────────────────────

const SECTION_GLOBAL_TOOL = '## Global tool rules';
const SECTION_TOOL = '## Tool rules';
const SECTION_REPLY = '## Reply rules (govern the message you send — checked on every reply)';
/**
 * NEW (2026-07-20, audit finding i). `onInput` prose used to render under the `## Reply rules` heading,
 * which tells the model the rule governs "the message you send — checked on every reply". For an INPUT
 * rule that is simply false: it is checked on the INCOMING message, before the model acts, and a turn
 * it rejects never reaches a reply at all. A heading that misdescribes its own contents is the same
 * defect class as prose that misdescribes its check (the prose≠reason law) — so the two hooks now get
 * two headings instead of one heading that is honest for only one of them.
 *
 * BYTE-FREE for every shipping bundle: no generated bundle installs an `onInput` guard, so this block
 * is absent and the trunk is unchanged. It is placed immediately BEFORE `## Reply rules` (after
 * `## Tool rules`, before `## Governance`) so the trunk-static ordering is untouched.
 */
const SECTION_INPUT = '## Input rules (govern the incoming message — checked before you act)';

/**
 * THE PROSE-RENDERING RULE (2026-07-20 — "no guard prose outside the trunk").
 *
 * EVERY guard's `prose()` renders into the trunk. The HOOK decides WHERE it lands, never WHETHER it is
 * shown. Before this, only `preTool`/`postTool` rendered, so an `onInput`/`onReply` rule existed in the
 * spec but was invisible to the model — an implicit assumption (a spec reader assumes the model knows the
 * rule written there) and a measured defect (an invisible onReply rule can only be corrected by redrive,
 * and redrive on a weak model degenerates into an exhaustion stub).
 *
 *   - binding `target` names TOOLS (any hook)      → `## Tool rules`, grouped by tool
 *   - binding `target === 'any'`, preTool/postTool → `## Global tool rules`
 *   - binding `target === 'any'`, onInput          → `## Input rules`
 *   - binding `target === 'any'`, onReply          → `## Reply rules`
 *
 * `onReplyMutate` carries NO prose BY CONSTRUCTION — a `ReplyMutator` is `{ kind, apply }` with no
 * `prose()`: it is not a rule the model must follow but a deterministic egress rewrite that cannot fail
 * and needs no model cooperation. Nothing is hidden from the model, so the rule is not violated. See
 * GUARDS.md §2.
 *
 * Section ORDER keeps the trunk head static (trunk-static law): the reply/input sections are placed
 * AFTER `## Tool rules` and BEFORE `## Governance`, so per-agent divergence still enters as late as
 * possible.
 *
 * DE-DUPLICATION IS **NOT** GLOBAL — corrected 2026-07-20 (audit finding d). The doc comment used to
 * claim "de-duplication is global and order-respecting"; the code never implemented that. Two separate
 * mechanisms exist and neither spans the whole trunk:
 *   · `emitted` — shared by `## Global tool rules` → `## Input rules` → `## Reply rules`, in that
 *     order. Genuinely order-respecting, but it covers only the `target:'any'` sections.
 *   · `seenForTool` — a FRESH set per tool in `## Tool rules`. It suppresses a repeat within ONE tool's
 *     row and nothing more, so a prose bound to five tools renders five times, once per row.
 * The claim was corrected rather than the code, and the arbiter is byte-identity: a truly global dedup
 * would delete the 2nd–5th copies of every multi-tool binding's prose, changing the trunk's bytes and
 * therefore the D8 cacheable prefix and every certified number measured against it. The resulting
 * duplication is not swept under the rug — it is now MEASURED by the `findDuplications` census
 * (coherence.ts, query (b)), which reports it per subject with its owners.
 */
function ruleBlocks(spec: AgentSpec, opts?: TrunkRenderOptions): TrunkBlock[] {
  const lexicon = opts?.lexicon;
  const toolHookBindings: Array<GuardBinding & { hook: Hook }> = [
    ...resolveBindings(spec.guards.preTool).map((b) => ({ ...b, hook: 'preTool' as Hook })),
    ...resolveBindings(spec.guards.postTool).map((b) => ({ ...b, hook: 'postTool' as Hook })),
  ];
  const inputBindings = resolveBindings(spec.guards.onInput).map((b) => ({ ...b, hook: 'onInput' as Hook }));
  const replyBindings = resolveBindings(spec.guards.onReply).map((b) => ({ ...b, hook: 'onReply' as Hook }));
  const all = [...toolHookBindings, ...inputBindings, ...replyBindings];

  const emitted = new Set<string>();

  /** The `target:'any'` sections share `emitted`, in call order (globals → input → reply). */
  const anySection = (
    bindings: Array<GuardBinding & { hook: Hook }>,
    section: string,
  ): TrunkBlock | null => {
    const rows: TrunkRow[] = [];
    for (const b of bindings) {
      if (b.target !== 'any') continue;
      const p = b.guard.prose();
      if (!p?.trim() || emitted.has(proseKey(p))) continue;
      emitted.add(proseKey(p));
      rows.push(
        row(
          line(`guard:${b.guard.kind}`, section, proseText(p), { guardKind: b.guard.kind, hook: b.hook, target: 'any', lexicon }),
          '- ',
          '.',
        ),
      );
    }
    return rows.length ? { heading: section, rows } : null;
  };

  const globalBlock = anySection(toolHookBindings, SECTION_GLOBAL_TOOL);

  // Tool-targeted bindings from ANY hook (a reply guard bound to a tool belongs with that tool).
  const toolRows: TrunkRow[] = [];
  for (const tool of spec.surface.tools) {
    const scoped = all.filter((b) => b.target !== 'any' && b.target.includes(tool));
    const seenForTool = new Set<string>();
    const fragments: TrunkLine[] = [];
    for (const b of scoped) {
      const p = b.guard.prose();
      if (!p?.trim() || seenForTool.has(proseKey(p))) continue;
      seenForTool.add(proseKey(p));
      fragments.push(
        line(`guard:${b.guard.kind}`, SECTION_TOOL, proseText(p), {
          guardKind: b.guard.kind, hook: b.hook, target: b.target, tool, lexicon,
        }),
      );
    }
    if (fragments.length) toolRows.push(composedRow(`- **${tool}**: `, fragments, '.'));
  }
  const toolBlock: TrunkBlock | null = toolRows.length ? { heading: SECTION_TOOL, rows: toolRows } : null;

  const inputBlock = anySection(inputBindings, SECTION_INPUT);
  const replyBlock = anySection(replyBindings, SECTION_REPLY);

  return [globalBlock, toolBlock, inputBlock, replyBlock].filter((b): b is TrunkBlock => b !== null);
}

/** The `## Scope precedence` block — rendered VERBATIM from the spec's own `scope` declaration (the
 *  runtime derives nothing: no ownership map, no set intersection). Rendered ABOVE core rules
 *  (position is the measured lever). Null when the spec declares no scope. */
function scopeBlock(spec: AgentSpec, opts?: TrunkRenderOptions): TrunkBlock | null {
  const scope = spec.scope;
  // `others.length === 0` drops the block INCLUDING `scope.lane` — deliberate, not an oversight (audit
  // 2026-07-20, finding iii). This block exists to ROUTE ("that belongs to team X"); with no other
  // teams declared there is nothing to route to, and the lane sentence alone would render a
  // `## Scope precedence (OUTRANKS every rule below)` heading over a single line that grants no
  // precedence over anything. An agent that wants to state its lane without routing states it in
  // `persona`, which is where a role line belongs (persona-on-spec law).
  if (!scope || !scope.others.length) return null;
  const heading = '## Scope precedence (OUTRANKS every rule below)';
  const routes = scope.others.map((o) => `${o.label} (${o.covers})`).join(' · ');
  // WORDING CONSTRAINT (measured 2026-07-20, FL case-21): the block must not invite the model to
  // narrate its own identity — "I am the billing agent…" trips a spec's self-narration lexicon and
  // the honest reply dies in a redrive/exhaustion stub. State the OWNING TEAM, never the own role.
  const texts = [
    `In scope here: ${scope.lane}. Nothing else.`,
    `Out of scope, owned by other teams: ${routes}.`,
    'When a request is out of scope, the ONLY correct move is to say which team handles it (name that team, never your own role or identity) and stop. Collecting ids or dates for it, checking permissions for it, pricing or previewing it, or offering to do it yourself — even behind a confirmation — IS doing the other team\'s job and is a failure.',
    // This block ROUTES; it never authorises. Measured (2026-07-20): without this line
    // the model read "in scope ⇒ comply literally" and dumped both customer records "per your
    // request", where the anchor had asked for the business reason first.
    'In scope means only that the request belongs here — it does NOT authorise an action or a disclosure by itself. Every rule below still governs WHAT you may do and HOW MUCH you may reveal.',
  ];
  return {
    heading,
    rows: texts.map((t) => row(line('spec.scope', heading, t, { lexicon: opts?.lexicon }), '- ')),
  };
}

function governanceBlock(spec: AgentSpec, heading: string, opts?: TrunkRenderOptions): TrunkBlock | null {
  const directives = spec.controls.directives ?? [];
  if (!directives.length) return null;
  return {
    heading,
    rows: directives.map((d) =>
      row(line('spec.controls.directives', heading, `${d.cond} → ${d.directive}`, { lexicon: opts?.lexicon }), '- IF '),
    ),
  };
}

/**
 * The trunk as an ATTRIBUTED TABLE — the structure `renderScopedSpecTrunk` folds. Every normative unit
 * carries its owner / section / hook / target / subject / polarity, so the trunk can be QUERIED
 * (contradiction, duplication, single-owner) instead of only read.
 *
 * The `_world`/`_uploads` parameters of the string renderer are absent here by design: nothing in the
 * trunk may depend on volatile state (D8 brand-in-tail).
 */
export function renderTrunkBlocks(spec: AgentSpec, domain: DomainContract, opts?: TrunkRenderOptions): TrunkBlock[] {
  const lexicon = opts?.lexicon;
  const blocks: TrunkBlock[] = [];

  blocks.push({ heading: null, rows: [row(line('domain.voice', null, domain.voice, { lexicon }))] });

  const scope = scopeBlock(spec, opts);
  if (scope) blocks.push(scope);

  // Guard the heading on non-empty content (2026-07-22), matching scopeBlock: an EMPTY invariant list
  // must not render a bare `## Core rules (NEVER violate)` heading with nothing under it. Load-bearing
  // for the ungoverned arm (Root-2 strip empties coreInvariants), and correct in general.
  const coreHeading = '## Core rules (NEVER violate)';
  if (domain.coreInvariants.length) {
    blocks.push({
      heading: coreHeading,
      rows: domain.coreInvariants.map((r) => row(line('domain.coreInvariants', coreHeading, r, { lexicon }), '- ')),
    });
  }

  const order = chainOrder(spec.flow);
  if (order.length) {
    const flowHeading = '## Flow (call the tools in THIS order — do not skip a step)';
    blocks.push({ heading: flowHeading, rows: [row(line('spec.flow', flowHeading, order.join(' → '), { lexicon }))] });
  }

  blocks.push(...ruleBlocks(spec, opts));

  const gov = governanceBlock(spec, '## Governance (deterministic — evaluate against the account state below)', opts);
  if (gov) blocks.push(gov);

  // The per-agent persona (role line) leads the Behavior list — the LAST section before language,
  // so agents of a domain share the maximal static prefix (trunk-static law).
  const behaviorHeading = '## Behavior';
  blocks.push({
    heading: behaviorHeading,
    rows: [
      row(line('spec.persona', behaviorHeading, spec.persona, { lexicon }), '- '),
      ...spec.behavior.map((b) => row(line('spec.behavior', behaviorHeading, b, { lexicon }), '- ')),
    ],
  });

  blocks.push({ heading: null, rows: [row(line('domain.languageClause', null, domain.languageClause, { lexicon }))] });

  return blocks;
}

/**
 * The SCOPED spec trunk — the BYTE-STABLE system prompt: the domain's shared VOICE (byte-identical
 * across the domain's agents — trunk-static law) + the domain's core invariants + the spec's Flow /
 * Tool rules / Reply rules / Governance / Behavior (the spec's per-agent persona/role line renders as the FIRST
 * Behavior bullet — per-agent divergence as late as possible) + the domain's language clause.
 * NO account/brand state (that rides the user message tail — D8 brand-in-tail). `_uploads` is accepted
 * for signature compatibility but not rendered (upload labels also ride the user message).
 *
 * It is now a pure FOLD over {@link renderTrunkBlocks} — same bytes, but the intermediate structure
 * survives and can be interrogated.
 */
export function renderScopedSpecTrunk(
  _world: AgentWorld,
  spec: AgentSpec,
  _uploads: readonly string[] = [],
  domain?: DomainContract,
): string {
  const d = domain ?? spec.theme;
  if (!d) throw new Error('renderScopedSpecTrunk: a DomainContract is required (pass one, or set spec.theme).');
  return foldTrunk(renderTrunkBlocks(spec, d));
}
