/**
 * @looprun/core — the DOMAIN-NEUTRAL trunk renderer + the `TrunkTheme` interface.
 *
 * This file contains ZERO business content — it is pure assembly machinery. Every business string
 * comes from a GENERATED artifact with exactly one owner: the AgentSpec (persona / Flow / Tool rules /
 * Governance / Behavior — per-agent) or the domain `TrunkTheme` (voice / core invariants / language /
 * state-render mapping — common to a business's agents). The per-agent persona (role line,
 * persona-on-spec law) lives on `spec.persona` and renders as the FIRST Behavior bullet; the shared
 * business `voice` lives on the theme and opens the trunk — byte-identical across the domain's agents
 * (trunk-static law: maximal shared prefix, per-agent divergence as late as possible).
 *
 * State-in-tail: `renderScopedSpecTrunk` renders ONLY case-invariant content, so the assembled
 * system prompt is BYTE-STABLE across cases/turns of an agent (→ cacheable prefix). The volatile
 * account/brand STATE (`theme.stateBlock`) is NOT rendered here — the runtime rides it on the USER
 * MESSAGE tail (like upload labels), keeping the stable prefix intact. For that to hold, a spec's
 * `persona` MUST be case-invariant (do not interpolate volatile world state into it).
 */
import { resolveBindings } from './spec.js';
import type { AgentSpec, GuardBinding } from './spec.js';
import type { AgentWorld } from './rules.js';

/** The DOMAIN skin: the business-COMMON strings NOT derived from any single AgentSpec. Ideally
 *  GENERATED by the agentspec skill from the business docs. Carries NO per-agent persona — that
 *  lives on `spec.persona` (persona-on-spec law). */
export interface TrunkTheme {
  /** The business VOICE paragraph — the trunk's opening. BYTE-IDENTICAL across every agent of the
   *  domain (trunk-static law: shared/static head, per-agent divergence as late as possible) and
   *  case-invariant (no volatile world state — cacheable prefix). */
  voice: string;
  /** The volatile account/brand-state block — rendered by the runtime onto the USER MESSAGE tail. */
  stateBlock(world: AgentWorld): string;
  /** The always-render "## Core rules (NEVER violate)" invariants. */
  coreInvariants: string[];
  /** The final "## Output language (ABSOLUTE)" clause. */
  languageClause: string;
  /** Deterministic honest-abstain closure (verified observations only). */
  exhaustionReply?: (world: AgentWorld, okTools: string[], produced: string[], violations: string[]) => string;
}

/** Linearize producer→consumer edges into an ordered node path (agent flows form simple chains). */
export function chainOrder(edges: { from: string; to: string }[]): string[] {
  if (!edges.length) return [];
  const succ = new Map<string, string>();
  const hasPred = new Set<string>();
  for (const e of edges) {
    succ.set(e.from, e.to);
    hasPred.add(e.to);
  }
  const start = edges.map((e) => e.from).find((n) => !hasPred.has(n)) ?? edges[0].from;
  const order: string[] = [];
  const seen = new Set<string>();
  let cur: string | undefined = start;
  while (cur && !seen.has(cur)) {
    order.push(cur);
    seen.add(cur);
    cur = succ.get(cur);
  }
  return order;
}

function ruleSections(spec: AgentSpec): { globalSection: string | null; toolSection: string | null } {
  const pre = resolveBindings(spec.guards.preTool);
  const post = resolveBindings(spec.guards.postTool);
  const all: GuardBinding[] = [...pre, ...post];

  const globals = all.filter((b) => b.target === 'any');
  const globalSection = globals.length
    ? `## Global tool rules\n${globals.map((b) => `- ${b.guard.prose()}.`).join('\n')}`
    : null;

  const lines: string[] = [];
  for (const tool of spec.surface.tools) {
    const scoped = all.filter((b) => b.target !== 'any' && b.target.includes(tool));
    if (scoped.length) lines.push(`- **${tool}**: ${scoped.map((b) => b.guard.prose()).join('; ')}.`);
  }
  const toolSection = lines.length ? `## Tool rules\n${lines.join('\n')}` : null;

  return { globalSection, toolSection };
}

function governanceSection(spec: AgentSpec, heading: string): string | null {
  const directives = spec.controls.directives ?? [];
  if (!directives.length) return null;
  return `${heading}\n${directives.map((d) => `- IF ${d.cond} → ${d.directive}`).join('\n')}`;
}

/**
 * The SCOPED spec trunk — the BYTE-STABLE system prompt: the theme's shared VOICE (byte-identical
 * across the domain's agents — trunk-static law) + the theme's core invariants + the spec's Flow /
 * Tool rules / Governance / Behavior (the spec's per-agent persona/role line renders as the FIRST
 * Behavior bullet — per-agent divergence as late as possible) + the theme's language clause.
 * NO account/brand state (that rides the user message tail — state-in-tail). `_uploads` is accepted
 * for signature compatibility but not rendered (upload labels also ride the user message).
 * The theme resolves host-injected first, then `spec.theme`.
 */
export function renderScopedSpecTrunk(
  _world: AgentWorld,
  spec: AgentSpec,
  _uploads: readonly string[] = [],
  theme?: TrunkTheme,
): string {
  const t = theme ?? spec.theme;
  if (!t) throw new Error('renderScopedSpecTrunk: a TrunkTheme is required (pass one, or set spec.theme).');
  const parts: string[] = [
    t.voice,
    `## Core rules (NEVER violate)\n${t.coreInvariants.map((r) => `- ${r}`).join('\n')}`,
  ];

  const order = chainOrder(spec.flow);
  if (order.length) parts.push(`## Flow (call the tools in THIS order — do not skip a step)\n${order.join(' → ')}`);

  const { globalSection, toolSection } = ruleSections(spec);
  if (globalSection) parts.push(globalSection);
  if (toolSection) parts.push(toolSection);

  const gov = governanceSection(spec, '## Governance (deterministic — evaluate against the account state below)');
  if (gov) parts.push(gov);

  // The per-agent persona (role line) leads the Behavior list — the LAST section before language,
  // so agents of a domain share the maximal static prefix (trunk-static law).
  const behaviorLines = [spec.persona, ...spec.behavior];
  parts.push(`## Behavior\n${behaviorLines.map((b) => `- ${b}`).join('\n')}`);

  parts.push(t.languageClause);

  return parts.join('\n\n');
}
