/**
 * FORMAT TEMPLATE for generated AgentSpecs — a FICTIONAL domain (plant nursery) so drafters can
 * learn the output shape WITHOUT reading any real/gold spec (reading gold specs contaminates
 * recall benchmarks and copies domain content instead of deriving it from THIS business's docs).
 *
 * Structure to reproduce: header comment (bucket + layer rationale) → class extending the layer →
 * super(config) → agent-layer guards → default export of a singleton.
 *
 * Placement: a real spec lands at `src/agents/<domain>/<agent>-spec.ts`, next to the domain's
 * generated `theme.ts`, and is registered in `src/agents/<domain>/index.ts` (the `SPECS` map +
 * `THEME` export the project's `looprun.eval.config.ts` imports).
 */
// Import surface: everything comes from 'looprun' (the umbrella re-export of @looprun-ai/core).
// See the kind vocabulary + signatures in references/guard-catalog.md (bundled).
import { AgentSpecBase, custom, jargonScrub, noFalseFailureClaim, precondition, requiresBefore, type AgentWorld } from 'looprun';
// The domain THEME (ONE shared object per domain — generated by E3, theme-generation.md).
import { NURSERY_THEME } from './theme.js';

// The domain's world seam narrows the opaque AgentWorld with the accessors THIS agent's guards read
// (the typed-world pattern — `precondition<W>` exists precisely so a domain narrows the world; no cast).
interface NurseryWorld extends AgentWorld {
  wateringQuotaRemaining(): number;
}

// LEXICON (P8a domain-neutrality law): @looprun-ai/core carries NO language-specific regex — every
// wording-keyed reply guard takes its pattern as a REQUIRED injected param. A real bundle keeps these
// in `src/agents/<domain>/lexicon.ts` (see examples/*/src/agents/*/lexicon.ts); inlined here so the
// template stays self-contained. This one matches a false "I couldn't do X" about an action that
// actually succeeded (inability phrase + a nursery action verb):
const FALSE_FAILURE_CLAIM_RE =
  /(cannot|can'?t|could ?not|couldn'?t|unable to|failed to|failed)[^.!?\n]{0,40}(water|repot|discard|schedul|list|record)/i;

export class AgentSpecNursery extends AgentSpecBase {
  constructor() {
    super({
      id: 'nursery-spec', // the `specs` map key in looprun.eval.config.ts; `--agent <id>` selects it
      mode: 'NURSERY_CARE',
      // REQUIRED per-agent persona (persona-on-spec law) — ONE role line: what THIS agent is/owns.
      // The runtime renders it as the FIRST Behavior bullet (trunk-static law: per-agent divergence
      // as late as possible; the shared business VOICE lives on the theme and opens the trunk).
      // Case-invariant.
      persona: 'You are the nursery-care agent: watering, repotting, and plant lifecycle.',
      // ≤15 tools, no terminal tools (replyToUser/askUser are the runner's, not yours).
      tools: ['listPlants', 'getWateringSchedule', 'waterPlant', 'repotPlant', 'discardPlant'],
      // Base layer ONLY because discardPlant carries a confirmed-flag protocol; else use Minimal.
      destructiveTools: ['discardPlant'],
      // Reference the domain theme so a host can construct this agent from the spec alone —
      // still ONE shared theme object per domain (a host-provided theme overrides it).
      theme: NURSERY_THEME,
      behavior: [
        // NO persona line here — persona is the config field above.
        // Every line CONDITIONED (Bucket-A): "when X, do Y" — never a bare state assertion.
        'Read schedules from getWateringSchedule — when the tool returns none, say so honestly; never invent dates.',
        'To discard a plant: locate its exact id first (listPlants); the tool returns a confirmation question — relay it and STOP until the user approves.',
        'If an action fails, report the REAL error briefly — never claim success that did not happen.',
        'When a message is garbled, recover with ONE concrete clarifying question.',
        "Keep replies short and in the user's language.",
      ],
    });

    // Spatial gate: repotting requires having looked at the plant list this conversation.
    this.addGuard('preTool', ['repotPlant'], requiresBefore(['listPlants']));

    // Run gate: precondition splits REASON (fires on deny) from PROSE (always rendered; states
    // the CONDITION — never asserts the current state).
    this.addGuard('preTool', ['waterPlant'], precondition<NurseryWorld>(
      (w) => w.wateringQuotaRemaining() > 0,
      'Daily watering quota exhausted — tell the user and offer tomorrow.',
      'watering needs remaining daily quota — when it is exhausted, say so and offer to schedule for tomorrow',
    ));

    // Behavior gate via custom(): EXISTENCE-keyed (observed calls), never user-text-keyed.
    this.addReplyCheck(custom({
      kind: 'noPhantomWatering',
      dim: 'behavior',
      check: (ctx) => {
        const watered = ctx.observed.some((o) => o.turnIndex === ctx.turnIndex && o.ok && o.name === 'waterPlant');
        if (watered) return null;
        return /\bwatered\b|\breguei\b/i.test(ctx.reply ?? '')
          ? 'You claimed watering happened but waterPlant did not succeed this turn — state what actually happened.'
          : null;
      },
      prose: () => 'only claim a plant was watered when the watering tool succeeded this turn',
    }), { id: 'agent:noPhantomWatering' });

    this.addReplyCheck(noFalseFailureClaim({ claimRe: FALSE_FAILURE_CLAIM_RE }), { id: 'agent:noFalseFailureClaim' });
    this.addMutator(jargonScrub({ 'spécimen': 'plant' }), { id: 'agent:jargonScrub' });
  }
}

export default new AgentSpecNursery();
